name: Build
on:
  push:
    branches:
      - master

jobs:
  website:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - run: mkdir -p build
      - run: npm i markdown-to-html-cli -g
      - run: markdown-to-html --output build/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - run: npm publish --access public --provenance
        name: 📦 loading-cli publish to NPM
        working-directory: core
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  